#!/data/data/com.termux/files/usr/bin/env bash

# update -- updates termux using apt and py modules using pip

keywords=("update" "upgrade" "autoremove")

pip2_updates () {
	if [[ -n "$(which pip2)" ]]; then
		pip2 install --upgrade pip

		pip_pkg="$(pip2 list -o --format=legacy | cut -d ' ' -f 1)"

		if [[ -n "$pip_pkg" ]]; then
			pip2 install --upgrade "$pip_pkg"
		fi
	fi
}

pip3_updates () {
	if [[ -n "$(which pip3)" ]]; then
		pip3 install --upgrade pip

		pip_pkg="$(pip3 list -o --format=legacy | cut -d ' ' -f 1)"

		if [[ -n "$pip_pkg" ]]; then
			pip3 install --upgrade "$pip_pkg"
		fi
	fi
}

updates () {
	for word in "${keywords[@]}"; do
		if [[ "upgrade" == "$word" || "autoremove" == "$word" ]]; then
			apt "$word" -y
		else
			apt "$word"
		fi
	done
}

updates

pip2_updates

pip3_updates
