:set number          " use numbered lines
:set background=dark " Use bright text colors against a dark background
:set tabstop=4       " The width of a TAB is set to 4.
                     " Still it is a \t. It is just that
                     " Vim will interpret it to be having
                     " a width of 4.
:set softtabstop=4   " Sets the number of columns for a TAB
:set shiftwidth=4    " Indents will have a width of 4
:set expandtab       " Expand TABs to spaces
:set autoindent      " Use automatic indentation
:syntax on           " Use syntax highlighting
